---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  type: NodePort
  selector:
    app: message-service
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  labels:
    app: message-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: message-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9091